# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Peer-Pressure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'

  # Pods for Peer-Pressure
  target 'Peer-PressureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Peer-PressureUITests' do
    # Pods for testing
  end

end
